<a href="https://colab.research.google.com/github/Twixii99/Machine-Learning---DataTalks/blob/main/Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1

In [427]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [428]:
np.__version__

'1.19.5'

# Question 2

In [429]:
pd.__version__

'1.1.5'

In [430]:
data_set = pd.read_csv('/content/drive/MyDrive/data.csv')

In [431]:
data_set

Make       Model  Year  ... city mpg  Popularity   MSRP
0          BMW  1 Series M  2011  ...       19        3916  46135
1          BMW    1 Series  2011  ...       19        3916  40650
2          BMW    1 Series  2011  ...       20        3916  36350
3          BMW    1 Series  2011  ...       18        3916  29450
4          BMW    1 Series  2011  ...       18        3916  34500
...        ...         ...   ...  ...      ...         ...    ...
11909    Acura         ZDX  2012  ...       16         204  46120
11910    Acura         ZDX  2012  ...       16         204  56670
11911    Acura         ZDX  2012  ...       16         204  50620
11912    Acura         ZDX  2013  ...       16         204  50920
11913  Lincoln      Zephyr  2006  ...       17          61  28995

[11914 rows x 16 columns]

In [432]:
data_set.columns.values

array(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size',
       'Vehicle Style', 'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype=object)

# Question 3

In [433]:
bmw = data_set.loc[data_set['Make'] == 'BMW']

In [434]:
bmw['MSRP'].mean()

61546.76347305389

# Question 4

In [435]:
cars_release_after_2015 = data_set.loc[data_set['Year'] >= 2015]

In [436]:
print(f'The number of cars before removing HP_engine missing values {cars_release_after_2015.shape[0]}')

The number of cars before removing HP_engine missing values 5995


In [437]:
cars_release_after_2015 = cars_release_after_2015.dropna(subset=['Engine HP'])

In [438]:
# cars_release_after_2015 = cars_release_after_2015.reset_index(drop=True)

In [439]:
print(f'The number of cars after removing HP_engine missing values {cars_release_after_2015.shape[0]}')

The number of cars after removing HP_engine missing values 5944


# Question 5

In [440]:
mean_of_HP_engine_before_fill = data_set['Engine HP'].mean()

In [441]:
print(f'the average of HP_engine before filling the missing rows = {round(mean_of_HP_engine_before_fill)}')

the average of HP_engine before filling the missing rows = 249


In [442]:
data_set_Q5 = data_set.fillna(value=mean_of_HP_engine)

In [443]:
mean_of_HP_engine_after_fill = data_set_Q5['Engine HP'].mean()

In [444]:
print(f'the average of HP_engine after filling the missing rows = {round(mean_of_HP_engine_after_fill)}')

the average of HP_engine after filling the missing rows = 249


# Question 6

In [445]:
Rolls_Royce = data_set.loc[data_set['Make'] == 'Rolls-Royce']

In [446]:
Rolls_Royce

Make                   Model  Year  ... city mpg  Popularity    MSRP
2921   Rolls-Royce                Corniche  2001  ...       10          86  359990
3505   Rolls-Royce                    Dawn  2016  ...       12          86  335000
5275   Rolls-Royce         Ghost Series II  2015  ...       13          86  286750
5276   Rolls-Royce         Ghost Series II  2015  ...       13          86  319400
5277   Rolls-Royce         Ghost Series II  2016  ...       13          86  295850
5278   Rolls-Royce         Ghost Series II  2016  ...       13          86  329325
5279   Rolls-Royce                   Ghost  2012  ...       13          86  250000
5280   Rolls-Royce                   Ghost  2012  ...       13          86  290000
5281   Rolls-Royce                   Ghost  2013  ...       13          86  296000
5282   Rolls-Royce                   Ghost  2013  ...       13          86  256650
5283   Rolls-Royce                   Ghost  2014  ...       13          86  263200
5284   Rolls-Royce                   Ghost  2014  ...       13          86  303300
7443   Rolls-Royce               Park Ward  2001  ...       11          86  259900
7444   Rolls-Royce               Park Ward  2002  ...       11          86  262990
7553   Rolls-Royce           Phantom Coupe  2014  ...       11          86  433550
7554   Rolls-Royce           Phantom Coupe  2015  ...       11          86  438325
7555   Rolls-Royce           Phantom Coupe  2016  ...       11          86  449525
7556   Rolls-Royce  Phantom Drophead Coupe  2014  ...       11          86  474600
7557   Rolls-Royce  Phantom Drophead Coupe  2015  ...       11          86  479775
7558   Rolls-Royce  Phantom Drophead Coupe  2016  ...       11          86  492000
7559   Rolls-Royce                 Phantom  2014  ...       11          86  402940
7560   Rolls-Royce                 Phantom  2014  ...       11          86  474990
7561   Rolls-Royce                 Phantom  2015  ...       11          86  407400
7562   Rolls-Royce                 Phantom  2015  ...       11          86  480175
7563   Rolls-Royce                 Phantom  2016  ...       11          86  417825
7564   Rolls-Royce                 Phantom  2016  ...       11          86  492425
9431   Rolls-Royce           Silver Seraph  2001  ...       11          86  219900
9432   Rolls-Royce           Silver Seraph  2002  ...       11          86  229990
11448  Rolls-Royce                  Wraith  2014  ...       13          86  284900
11449  Rolls-Royce                  Wraith  2015  ...       13          86  294025
11450  Rolls-Royce                  Wraith  2016  ...       13          86  304350

[31 rows x 16 columns]

In [447]:
Rolls_Royce = Rolls_Royce[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [448]:
Rolls_Royce

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [449]:
Rolls_Royce = Rolls_Royce.drop_duplicates()

In [450]:
Rolls_Royce

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [451]:
X = Rolls_Royce.to_numpy()

In [452]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [453]:
X.shape

(7, 3)

In [454]:
XTX = np.dot(X.T, X)

In [455]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [456]:
XTX.shape

(3, 3)

In [457]:
XTX = np.linalg.inv(XTX) 

In [458]:
XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [459]:
XTX.sum()

0.032212320677486125

# Questions 7

In [460]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [461]:
y = np.array(y)

In [462]:
y = y.reshape((1,7))

In [463]:
y.shape

(1, 7)

In [464]:
w = np.dot(XTX, X.T)

In [465]:
w.shape

(3, 7)

In [466]:
w = np.dot(w, y.T)

In [467]:
w

array([[ 0.19989598],
       [31.02612262],
       [31.65378877]])